DROP DATABASE IF EXISTS quilt_db;

CREATE DATABASE quilt_db;

USE quilt_db;

CREATE TABLE info (
id INTEGER NOT NULL AUTO_INCREMENT,
email VARCHAR(40) NOT NULL,
password VARCHAR(20) NOT NULL,
PRIMARY KEY (id)
);